[project]
name = "fastapi-learning-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sajad Hatami", email = "sajadhatamiw@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.19.1",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.141.1",
    "pwdlib[argon2]>=0.3.1",
    "pydantic-settings>=2.15.0",
    "pyjwt>=2.13.0",
    "scalar-fastapi>=1.9.0",
    "sqlalchemy>=2.0.52",
]

[project.scripts]
fastapi-learning-project = "fastapi_learning_project:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
